version: '3.0'

expectations:
  population_size: 10000

actions:   

  generate_study_population_os_reports:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_os_reports --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/os_reports/input_os_reports.feather
          
  os_report_charts:
    run: r:latest analysis/10_eol_service_report_charts.R
    needs: [generate_study_population_os_reports]
    outputs:
      moderately_sensitive:
        monthly_deaths_place: output/os_reports/eol_service/deaths_month.csv
        monthly_deaths_place_plot: output/os_reports/eol_service/deaths_month_plot.png
        monthly_gp_place: output/os_reports/eol_service/gp_month.csv
        monthly_gp_place_plot: output/os_reports/eol_service/gp_month_plot.png
        monthly_aevis_place: output/os_reports/eol_service/aevis_month.csv
        monthly_aevis_place_plot: output/os_reports/eol_service/aevis_month_plot.png

  os_report:
    run: r:latest analysis/10b_eol_service_report_html.R
    needs: [os_report_charts]
    outputs:
      moderately_sensitive:
        os_report: output/os_reports/eol_service/eol_service_report.html
