version: '3.0'

expectations:
  population_size: 10000

actions:   

  generate_study_population_os_reports:
    run: ehrql:v0 generate-dataset analysis/os_reports/dataset_definition_os_reports.py --output output/os_reports/input_os_reports.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/os_reports/input_os_reports.csv.gz
           
  os_report_charts:
    run: r:latest analysis/os_reports/01_eol_service_report_charts.R
    needs: [generate_study_population_os_reports]
    outputs:
      moderately_sensitive:
        monthly_deaths_place: output/os_reports/eol_service/deaths_month.csv
        monthly_deaths_place_plot: output/os_reports/eol_service/deaths_month_plot.png
        eol_med_place: output/os_reports/eol_service/eol_med_pod.csv
        eol_med_place_plot: output/os_reports/eol_service/eol_med_plot.png
        monthly_gp_place: output/os_reports/eol_service/gp_month.csv
        monthly_gp_place_plot: output/os_reports/eol_service/gp_month_plot.png
        monthly_aevis_place: output/os_reports/eol_service/aevis_month.csv
        monthly_aevis_place_plot: output/os_reports/eol_service/aevis_month_plot.png
        monthly_op_place: output/os_reports/eol_service/opapp_month.csv
        monthly_op_place_plot: output/os_reports/eol_service/opapp_month_plot.png

  os_report:
    run: r:latest analysis/os_reports/03_eol_service_report_html.R
    needs: [os_report_charts]
    outputs:
      moderately_sensitive:
        os_report: output/os_reports/eol_service/eol_service_report.html
