version: '3.0'

expectations:
  population_size: 10000

actions:   

  generate_study_population_os_reports:
    run: ehrql:v0 generate-dataset analysis/os_reports/dataset_definition_os_reports.py --output output/os_reports/input_os_reports.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/os_reports/input_os_reports.csv.gz
           
  os_report_charts:
    run: r:latest analysis/os_reports/01_eol_service_report_charts.R
    needs: [generate_study_population_os_reports]
    outputs:
      moderately_sensitive:
        monthly_deaths_place: output/os_reports/eol_service/deaths_month.csv
        monthly_deaths_place_plot: output/os_reports/eol_service/deaths_month_plot.png
        monthly_gp_timeseries: output/os_reports/eol_service/gp_month_*.png
        monthly_gp_CSV: output/os_reports/eol_service/gp_month*.csv
        monthly_gp_Count: output/os_reports/eol_service/gp_count*.csv
        monthly_med_timeseries: output/os_reports/eol_service/eol_med_*.png
        monthly_med_CSV: output/os_reports/eol_service/eol_med*.csv
        monthly_med_Count: output/os-reports/eol_service/eol_count*.csv
        monthly_aevis_timeseries: output/os_reports/eol_service/aevis_month_*.png
        monthly_aevis_CSV: output/os_reports/eol_service/aevis_month*.csv
        monthly_aevis_Count: output/os_reports/eol_service/aevis_count*.csv
        monthly_op_timeseries: output/os_reports/eol_service/opapp_month_*.png          
        monthly_op_CSV: output/os_reports/eol_service/opapp_month*.csv
        monthly_op_Count: output/os_reports/eol_service/opapp_count*.csv
        monthly_eladm_timeseries: output/os_reports/eol_service/eladm_month_*.png   
        monthly_eladm_CSV: output/os_reports/eol_service/eladm_month*.csv
        monthly_eladm_Count: output/os_reports/eol_service/eladm_count*.csv
        monthly_emadm_timeseries: output/os_reports/eol_service/emadm_month_*.png   
        monthly_emadm_CSV: output/os_reports/eol_service/emadm_month*.csv
        monthly_emadm_Count: output/os_reports/eol_service/emadm_count*.csv
        monthly_nursing_timeseries: output/os_reports/eol_service/nursing_month_*.png
        monthly_nursing_CSV: output/os_reports/eol_service/nursing_month*.csv 
        montly_nursing_Count: output/os_reports/eol_service/nursing_count*.csv


  os_report:
    run: r:latest analysis/os_reports/03_eol_service_report_html.R
    needs: [os_report_charts]
    outputs:
      moderately_sensitive:
        os_report: output/os_reports/eol_service/eol_service_report.html
